### ISSUE TITLE
博客上的一些小小建议

### ISSUE THREAD

**Issue by einverne** [ResolveWang/myblog#1]
从你的博客学习到了不少，最近的一篇文章 git 撤销之前的提交，应该还有另外一个方法 `git rebase`。我看使用的是畅言，不想留下手机号，所以原谅我用 GitHub 的 issue。

**Comment by ResolveWang** [comment]
感谢认可。我觉得`rebase`的主要功能应该是和`merge`类似，主要用于做分支整合，只不过它会拉平分支的commit

**Comment by einverne** [comment]
但是比如说 commit1- commit2- commit3  想要撤销 commit2 通过 reset 是不行的，而通过 revert 会多一个 revert-commit2 的提交，而通过 git rebase -i HEAD~3 然后 drop 掉commit2 就行了。这是我的想法。

**Comment by ResolveWang** [comment]
刚才我做了一下实验，发现`git rebase -i`确实可以实现这个功能，感谢补充
